### PR TITLE
Create Occitan wordlist

### PR DESCRIPTION
**Pull request by Mejans**
List of 10 000 most used words in Occitan language

### CODE REVIEW

**Review by oprogramador — APPROVED** [review]

**Comment by oprogramador** [comment]
Thanks @Mejans 

This update should be available in the `3.0.14` NPM version.

Btw. could you provide the source of your list?

**Comment by Mejans** [comment]
Sure, it comes from my website:
https://www.mejans.fr/article/lista-de-mots-mai-frequents-en-occitan.html
If you add credits, it can be : Quentin PAGÈS & Lo Congrès

**Comment by oprogramador** [comment]
Thanks.

For now, I don't add the source to the README because I found there only a .7z file. I'd like to have just a txt or zip.

Anyway, you're already in the list of contributors of this repo.

Btw. I see that the Occitan list is similar to the Catalan list.

**Comment by Mejans** [comment]
We share something like 70% of our vocabulary I think.
https://en.wikipedia.org/wiki/Occitan_language

**Pull request merged**
